CREATE TABLE users (
    id CHAR(40) PRIMARY KEY NOT NULL,
    nome VARCHAR(200) NOT NULL,
    foto_usuario VARCHAR(1500) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    senha CHAR(60) NOT NULL,
    is_admin BOOLEAN NOT NULL DEFAULT FALSE,
    telefone VARCHAR(20),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE appointments (
    id INT PRIMARY KEY AUTO_INCREMENT,
    titulo VARCHAR(255) NOT NULL,
    descricao TEXT,
    data_marcada DATETIME NOT NULL,
    data_termino DATETIME NOT NULL,
    data_bloqueda BOOLEAN NOT NULL DEFAULT FALSE,

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    
    usuario_id CHAR(40),
    FOREIGN KEY (usuario_id) REFERENCES users(id)
);